// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig(arg1, arg2) {
  return window['go']['main']['App']['GetConfig'](arg1, arg2);
}

export function ScanPorts(arg1) {
  return window['go']['main']['App']['ScanPorts'](arg1);
}

export function WriteConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WriteConfig'](arg1, arg2, arg3, arg4);
}
