// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig(arg1:string,arg2:number):Promise<main.DeviceConfigResponse>;

export function ScanPorts(arg1:number):Promise<Array<main.DeviceSummary>>;

export function WriteConfig(arg1:string,arg2:number,arg3:Record<string, any>,arg4:boolean):Promise<main.WriteConfigResponse>;
